#: Text cursor customization {{{
# cursor #cccccc
# cursor_text_color #111111

# url_color #0087bd
# url_style curly
#: The color and style for highlighting URLs on mouse-over. url_style
#: can be one of: none, straight, double, curly, dotted, dashed.

#: Color scheme {{{
# foreground #dddddd
# background #000000
background_opacity 0.5
# background_blur 0 (<64)
# selection_foreground #000000
# selection_background #fffacd

#: The foreground and background colors for text selected with the
#: mouse. Setting both of these to none will cause a "reverse video"
#: effect for selections, where the selection will be the cell text
#: color and the text will become the cell background color. Setting
#: only selection_foreground to none will cause the foreground color
#: to be used unchanged. Note that these colors can be overridden by
#: the program running in the terminal.

#: The color table {{{

#: The 256 terminal colors. There are 8 basic colors, each color has a
#: dull and bright version, for the first 16 colors. You can set the
#: remaining 240 colors as color16 to color255.

# color0 #000000
# color8 #767676
#: black

# color1 #cc0403
# color9 #f2201f
#: red

# color2  #19cb00
# color10 #23fd00
#: green

# color3  #cecb00
# color11 #fffd00
#: yellow

# color4  #0d73cc
# color12 #1a8fff
#: blue

# color5  #cb1ed1
# color13 #fd28ff
#: magenta

# color6  #0dcdcd
# color14 #14ffff
#: cyan

# color7  #dddddd
# color15 #ffffff
#: white

# mark1_foreground black
#: Color for marks of type 1

# mark1_background #98d3cb
#: Color for marks of type 1 (light steel blue)

# mark2_foreground black
#: Color for marks of type 2

# mark2_background #f2dcd3
#: Color for marks of type 1 (beige)

# mark3_foreground black
#: Color for marks of type 3

# mark3_background #f274bc
#: Color for marks of type 3 (violet)

linux_display_server wayland

font_family      family='JetBrainsMono Nerd Font' postscript_name=JetBrainsMonoNF-Thin
bold_font        family='JetBrainsMono Nerd Font' postscript_name=JetBrainsMonoNF-SemiBold
italic_font      family='JetBrainsMono Nerd Font' postscript_name=JetBrainsMonoNF-ThinItalic
bold_italic_font family='JetBrainsMono Nerd Font' postscript_name=JetBrainsMonoNF-SemiBoldItalic

